### PR TITLE
declare automatic module name

### PR DESCRIPTION
**Pull request by kopavel**

### CODE REVIEW

**Review by codesqueak — COMMENTED** [review]
Why would I want to do this ? 
Performance impact  / test ?

**Review by codesqueak — COMMENTED** [review]
Why?

**Review by codesqueak — COMMENTED** [review]
Not seeing what this gives me ?
Not seeing any tests for the new code
Changes to Z80Core seem incomplete - why change just for one type of instruction ?

**Review by codesqueak — COMMENTED** [review]
Why do I want to use jitpack ? what does it give me that I don't already have

**Review by codesqueak — COMMENTED** [review]
Lots of changes, not seeing any performance test info. What impact does it have on performance, if any ?

**Review by codesqueak — COMMENTED** [review]
Nope. I'm happy with import .* - No one is going to read all those imports ...

**Comment by kopavel** [comment]
?? i'm ack to merge only automatic module - not all other stuff... o__O 
literally only 07fee01e21a988a25ffc57009efa2f429b2c6a0a commit.
All other stuff i do for my only purpose, for use in my personal project... 
May be I not yet fully understand "GitHub Pull Request" functionality...

**Pull request closed without merging**
